<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projeto de PHP </title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <!-- Body -->
    <div class="container-fluid">
        <div class="row flex-nowrap">
            <!-- Chamando a Side-Bar do sistema -->
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 pt-4 mvh-100 bg-white shadow-sm">
        <div class="container">
            <div class="div d-flex flex-column align-items-center justify-content-center mt-4 gap-2">
                <img style="width: 48px;" src="/img/avatar.png" alt="">
                <div class="texts div d-flex flex-column align-items-center justify-content-center">
                    <h6> Projeto PHP</h6>
                    <p class="small">Administrador</p>
                </div>
            </div>
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start w-100" id="menu">
                    <!-- Home - Retroflix -->
                    <li class="nav-item w-100 ">
                        <a href="/" class="nav-link align-middle px-0">
                            <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Início</span>
                        </a>
                    </li>
                    <!-- Gerenciar -->
                    <li class="nav-item w-100">
                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                            <i class="fs-4 bi bi-pencil-square"></i> <span class="ms-1 d-none d-sm-inline">Gerenciar</span> </a>
                        <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="/clientes/" class="nav-link px-0 text-body"> <span class="d-none d-sm-inline">Clientes</span></a>
                            </li>
                            <li class="w-100">
                                <a href="/seller/" class="nav-link px-0 text-body"> <span class="d-none d-sm-inline">Fornecedores</span></a>
                            </li>
                            <li class="w-100">
                                <a href="/produtos/" class="nav-link px-0 text-body"> <span class="d-none d-sm-inline">Produtos</span></a>
                            </li>
                            <li class="w-100">
                                <a href="/funcionarios/" class="nav-link px-0 text-body"> <span class="d-none d-sm-inline">Funcionários</span></a>
                            </li>
                            <li class="w-100">
                                <a href="/produtos/" class="nav-link px-0 text-body"> <span class="d-none d-sm-inline">Produtos</span></a>
                            </li>
                        </ul>
                    </li>

            </div>
        </div>
    </div>
            <!-- Conteúdo do site -->
            <div class="col-auto col-md-9 ms-5 mt-4 bg-light py-3">
                <h2>Dashboard</h2>
                <p class="text-body small">
                    Confira os mais recentes resultados obtidos.
                </p>
                <!-- Cards de destaques - Dashboard -->

                <!-- Tabela de destaque - Locações recentes -->
                <div class="mt-5">
                    <h5>Clientes</h5>
                    <div class="shadow-sm">
                        <table class="table table-hover  rounded">
                            <thead class="bg-white">
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Sobrenome</th>
                                    <th scope="col">Idade</th>
                                </tr>
                            </thead>
                            <tbody class="">
                                <tr>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            </div>
        </div>
    </div>

</body>

</html>
